const express = require("express");
const router = express.Router();
const pool = require("../database");

// Crear nuevo registro de excavación
router.post("/excavacion", async (req, res) => {
  try {
    const {
      id_permiso,
      tipo_mantenimiento,
      ot_numero,
      tag,
      hora_inicio,
      equipo_intervenir,
      descripcion_trabajo,
      nombre_solicitante,
      empresa,
      profundidad_media,
      profundidad_maxima,
      anchura,
      longitud,
      tipo_terreno,
      tuberia_gas,
      tipo_gas,
      comprobado_gas,
      fecha_gas,
      linea_electrica,
      voltaje_linea,
      comprobado_electrica,
      fecha_electrica,
      tuberia_incendios,
      presion_incendios,
      comprobado_incendios,
      fecha_incendios,
      alcantarillado,
      diametro_alcantarillado,
      comprobado_alcantarillado,
      fecha_alcantarillado,
      otras_instalaciones,
      especificacion_otras_instalaciones,
      comprobado_otras,
      fecha_otras,
      requiere_talud,
      angulo_talud,
      requiere_bermas,
      longitud_meseta,
      altura_contrameseta,
      requiere_entibacion,
      tipo_entibacion,
      condiciones_terreno_entibacion,
      otros_requerimientos,
      especificacion_otros_requerimientos,
      distancia_seguridad_estatica,
      distancia_seguridad_dinamica,
      requiere_balizamiento,
      distancia_balizamiento,
      requiere_proteccion_rigida,
      distancia_proteccion_rigida,
      requiere_senalizacion_especial,
      especificacion_senalizacion,
      requiere_proteccion_anticaida,
      tipo_proteccion_anticaida,
      tipo_anclaje,
      excavacion_espacio_confinado,
      numero_permiso_confinado,
      excavacion_manual_aproximacion,
      medidas_aproximacion,
      herramienta_antichispa,
      guantes_calzado_dielectrico,
      epp_especial,
      otras_medidas_especiales,
      especificacion_otras_medidas_especiales,
      aplicar_bloqueo_fisico,
      especificacion_bloqueo_fisico,
      drenar_limpiar_lavar,
      inundar_anegar_atmosfera_inerte,
      vigilante_continuo,
      especificacion_vigilante_continuo,
      otras_medidas_adicionales,
      especificacion_otras_medidas_adicionales,
      observaciones_generales_excavacion,
    } = req.body;

    const columnas = [
      "id_permiso",
      "tipo_mantenimiento",
      "ot_numero",
      "tag",
      "hora_inicio",
      "equipo_intervenir",
      "descripcion_trabajo",
      "nombre_solicitante",
      "empresa",
      "profundidad_media",
      "profundidad_maxima",
      "anchura",
      "longitud",
      "tipo_terreno",
      "tuberia_gas",
      "tipo_gas",
      "comprobado_gas",
      "fecha_gas",
      "linea_electrica",
      "voltaje_linea",
      "comprobado_electrica",
      "fecha_electrica",
      "tuberia_incendios",
      "presion_incendios",
      "comprobado_incendios",
      "fecha_incendios",
      "alcantarillado",
      "diametro_alcantarillado",
      "comprobado_alcantarillado",
      "fecha_alcantarillado",
      "otras_instalaciones",
      "especificacion_otras_instalaciones",
      "comprobado_otras",
      "fecha_otras",
      "requiere_talud",
      "angulo_talud",
      "requiere_bermas",
      "longitud_meseta",
      "altura_contrameseta",
      "requiere_entibacion",
      "tipo_entibacion",
      "condiciones_terreno_entibacion",
      "otros_requerimientos",
      "especificacion_otros_requerimientos",
      "distancia_seguridad_estatica",
      "distancia_seguridad_dinamica",
      "requiere_balizamiento",
      "distancia_balizamiento",
      "requiere_proteccion_rigida",
      "distancia_proteccion_rigida",
      "requiere_senalizacion_especial",
      "especificacion_senalizacion",
      "requiere_proteccion_anticaida",
      "tipo_proteccion_anticaida",
      "tipo_anclaje",
      "excavacion_espacio_confinado",
      "numero_permiso_confinado",
      "excavacion_manual_aproximacion",
      "medidas_aproximacion",
      "herramienta_antichispa",
      "guantes_calzado_dielectrico",
      "epp_especial",
      "otras_medidas_especiales",
      "especificacion_otras_medidas_especiales",
      "aplicar_bloqueo_fisico",
      "especificacion_bloqueo_fisico",
      "drenar_limpiar_lavar",
      "inundar_anegar_atmosfera_inerte",
      "vigilante_continuo",
      "especificacion_vigilante_continuo",
      "otras_medidas_adicionales",
      "especificacion_otras_medidas_adicionales",
      "observaciones_generales_excavacion",
    ];
    const valores = [
      id_permiso,
      tipo_mantenimiento,
      ot_numero,
      tag,
      hora_inicio,
      equipo_intervenir,
      descripcion_trabajo,
      nombre_solicitante,
      empresa,
      profundidad_media,
      profundidad_maxima,
      anchura,
      longitud,
      tipo_terreno,
      tuberia_gas,
      tipo_gas,
      comprobado_gas,
      fecha_gas || null,
      linea_electrica,
      voltaje_linea,
      comprobado_electrica,
      fecha_electrica || null,
      tuberia_incendios,
      presion_incendios,
      comprobado_incendios,
      fecha_incendios || null,
      alcantarillado,
      diametro_alcantarillado,
      comprobado_alcantarillado,
      fecha_alcantarillado || null,
      otras_instalaciones,
      especificacion_otras_instalaciones,
      comprobado_otras,
      fecha_otras || null,
      requiere_talud,
      angulo_talud,
      requiere_bermas,
      longitud_meseta,
      altura_contrameseta,
      requiere_entibacion,
      tipo_entibacion,
      condiciones_terreno_entibacion,
      otros_requerimientos,
      especificacion_otros_requerimientos,
      distancia_seguridad_estatica,
      distancia_seguridad_dinamica,
      requiere_balizamiento,
      distancia_balizamiento,
      requiere_proteccion_rigida,
      distancia_proteccion_rigida,
      requiere_senalizacion_especial,
      especificacion_senalizacion,
      requiere_proteccion_anticaida,
      tipo_proteccion_anticaida,
      tipo_anclaje,
      excavacion_espacio_confinado,
      numero_permiso_confinado,
      excavacion_manual_aproximacion,
      medidas_aproximacion,
      herramienta_antichispa,
      guantes_calzado_dielectrico,
      epp_especial,
      otras_medidas_especiales,
      especificacion_otras_medidas_especiales,
      aplicar_bloqueo_fisico,
      especificacion_bloqueo_fisico,
      drenar_limpiar_lavar,
      inundar_anegar_atmosfera_inerte,
      vigilante_continuo,
      especificacion_vigilante_continuo,
      otras_medidas_adicionales,
      especificacion_otras_medidas_adicionales,
      observaciones_generales_excavacion,
    ];

    console.log("Número de columnas:", columnas.length);
    console.log("Número de valores:", valores.length);

    const query = `
INSERT INTO pt_excavacion (
  id_permiso, tipo_mantenimiento, ot_numero, tag, hora_inicio, equipo_intervenir, descripcion_trabajo, nombre_solicitante, empresa,
  profundidad_media, profundidad_maxima, anchura, longitud, tipo_terreno,
  tuberia_gas, tipo_gas, comprobado_gas, fecha_gas,
  linea_electrica, voltaje_linea, comprobado_electrica, fecha_electrica,
  tuberia_incendios, presion_incendios, comprobado_incendios, fecha_incendios,
  alcantarillado, diametro_alcantarillado, comprobado_alcantarillado, fecha_alcantarillado,
  otras_instalaciones, especificacion_otras_instalaciones, comprobado_otras, fecha_otras,
  requiere_talud, angulo_talud,
  requiere_bermas, longitud_meseta, altura_contrameseta,
  requiere_entibacion, tipo_entibacion, condiciones_terreno_entibacion,
  otros_requerimientos, especificacion_otros_requerimientos,
  distancia_seguridad_estatica, distancia_seguridad_dinamica,
  requiere_balizamiento, distancia_balizamiento,
  requiere_proteccion_rigida, distancia_proteccion_rigida,
  requiere_senalizacion_especial, especificacion_senalizacion,
  requiere_proteccion_anticaida, tipo_proteccion_anticaida, tipo_anclaje,
  excavacion_espacio_confinado, numero_permiso_confinado,
  excavacion_manual_aproximacion, medidas_aproximacion,
  herramienta_antichispa, guantes_calzado_dielectrico, epp_especial, otras_medidas_especiales, especificacion_otras_medidas_especiales,
  aplicar_bloqueo_fisico, especificacion_bloqueo_fisico, drenar_limpiar_lavar, inundar_anegar_atmosfera_inerte, vigilante_continuo, especificacion_vigilante_continuo, otras_medidas_adicionales, especificacion_otras_medidas_adicionales, observaciones_generales_excavacion
) VALUES (
  $1,$2,$3,$4,$5,$6,$7,$8,$9,
  $10,$11,$12,$13,$14,
  $15,$16,$17,$18,
  $19,$20,$21,$22,
  $23,$24,$25,$26,
  $27,$28,$29,$30,
  $31,$32,$33,$34,
  $35,$36,
  $37,$38,$39,
  $40,$41,$42,
  $43,$44,
  $45,$46,
  $47,$48,
  $49,$50,
  $51,$52,
  $53,$54,$55,
  $56,$57,
  $58,$59,
  $60,$61,$62,$63,$64,
  $65,$66,$67,$68,$69,$70,$71,$72,$73
) RETURNING id;
`;

    const result = await pool.query(query, valores);
    res.status(201).json({
      success: true,
      message: "Permiso de excavación creado exitosamente",
      id: result.rows[0].id,
    });
  } catch (err) {
    console.error(err);
    res
      .status(500)
      .json({ error: "Error al guardar el permiso de excavación" });
  }
});

module.exports = router;
